# Generated by Django 4.2.2 on 2023-08-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Komanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miestas', models.CharField(max_length=50, verbose_name='Miestas')),
                ('pavadinimas', models.CharField(max_length=50, verbose_name='Komandos pavadinimas')),
                ('ikurimo_data', models.IntegerField(verbose_name='Klubas įkurtas')),
                ('saka', models.CharField(max_length=50, verbose_name='Sporto šaka')),
            ],
        ),
    ]
