# Generated by Django 4.2.2 on 2023-08-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komanda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaidejas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=50, verbose_name='Žaidėjo vardas')),
                ('pavarde', models.CharField(max_length=50, verbose_name='Žaidėjo pavardė')),
                ('pozicija', models.CharField(max_length=20, verbose_name='Žaidėjo pozicija')),
                ('amzius', models.IntegerField(verbose_name='Žaidėjo amžius')),
                ('komanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zaidejas_set', to='komanda.komanda')),
            ],
        ),
    ]
